version: '3.8'


services:
  app:
    build: .
    volumes:
      - ./db:/wd/db:rw
    ports:
      - "8000:8000"
    user: "1000"
    command: bash -c "make migrate && python manage.py runserver 0.0.0.0:8000"