version: '3.8'

volumes:
  postgres_data: { }

services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    profiles:
      - full_dev

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    profiles:
      - full_dev
      - local_dev
