# Generated by Django 4.1.5 on 2023-02-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_kind_animal_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="kind",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="animals.kind",
            ),
        ),
    ]
