# Generated by Django 4.1.7 on 2023-03-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animals", "0003_rename_session_owner_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
