# Generated by Django 4.1.7 on 2023-02-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0005_animal_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="animal",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="animals.kind",
            ),
        ),
    ]
